-- =====================================================================
-- CONTRATOS DE PRESTACION DE SERVICIOS
--
-- Genera el contrato automatico cuando un plan de trabajo queda armado
-- con mas de 3 fechas de servicio programadas.
--
-- Idempotente: se puede correr mas de una vez sin romper nada.
--
-- IMPORTANTE: este archivo NO trae los datos fiscales ni bancarios de
-- Fumigaciones AECO escritos aqui adentro, a proposito. El repositorio
-- de esta app es publico en GitHub, asi que el RFC, el registro patronal,
-- la cuenta y la CLABE se capturan UNA SOLA VEZ desde la pestaña
-- "Empresa" de la aplicacion (se guardan en la base de datos, que si es
-- privada). Nunca los pegues en este archivo.
-- =====================================================================


-- ---------------------------------------------------------------------
-- PASO 1. Datos del PRESTADOR que pide el contrato y que hoy no existen
-- en configuracion_empresa. Se quedan en null: se llenan desde la app.
-- ---------------------------------------------------------------------
alter table public.configuracion_empresa add column if not exists rfc                      text;
alter table public.configuracion_empresa add column if not exists registro_patronal_imss   text;
alter table public.configuracion_empresa add column if not exists registro_stps            text;
alter table public.configuracion_empresa add column if not exists domicilio_legal          text;
alter table public.configuracion_empresa add column if not exists actividad_preponderante  text;
alter table public.configuracion_empresa add column if not exists representante_legal      text;
alter table public.configuracion_empresa add column if not exists banco_cuenta             text;
alter table public.configuracion_empresa add column if not exists banco_clabe              text;
alter table public.configuracion_empresa add column if not exists contrato_garantia_dias   integer;
alter table public.configuracion_empresa add column if not exists contrato_ciudad_firma    text;


-- ---------------------------------------------------------------------
-- PASO 2. Tabla de contratos.
--
-- Las columnas sueltas son solo para poder listar, filtrar y ordenar
-- rapido (folio, cliente, vigencia, montos, estatus). El contrato
-- completo tal como se imprimio -- razon social, domicilio fiscal,
-- representante legal del cliente, calendario de visitas, productos,
-- clausulas y los datos del prestador vigentes ese dia -- se guarda
-- congelado en "datos" (jsonb). De esa forma un contrato ya firmado
-- se sigue reimprimiendo IGUAL aunque despues cambien los datos del
-- cliente, los precios o la configuracion de la empresa.
-- ---------------------------------------------------------------------
create table if not exists public.contratos (
  id                    uuid primary key default gen_random_uuid(),
  folio                 bigint generated by default as identity unique,
  cliente_id            uuid not null references public.clientes(id),
  servicio_id           uuid references public.servicios_cliente(id),
  fecha_contrato        date not null default current_date,
  vigencia_inicio       date,
  vigencia_fin          date,
  num_servicios         integer,
  monto_total_sin_iva   numeric,
  monto_mensual_sin_iva numeric,
  datos                 jsonb not null,
  estatus               text not null default 'Vigente'
                        check (estatus in ('Vigente','Terminado','Cancelado')),
  creado_por            uuid references auth.users(id),
  fecha_creacion        timestamptz not null default now(),
  fecha_actualizacion   timestamptz not null default now()
);

create index if not exists idx_contratos_cliente  on public.contratos (cliente_id);
create index if not exists idx_contratos_servicio on public.contratos (servicio_id);
create index if not exists idx_contratos_vigencia on public.contratos (vigencia_inicio, vigencia_fin);

-- Mantiene fecha_actualizacion al dia (reusa la funcion que ya existe
-- en supabase-setup.sql para cotizaciones y configuracion_empresa).
drop trigger if exists trg_contratos_fecha_actualizacion on public.contratos;
create trigger trg_contratos_fecha_actualizacion
  before update on public.contratos
  for each row execute function public.actualizar_fecha_actualizacion();


-- ---------------------------------------------------------------------
-- PASO 3. RLS: mismo patron de equipo compartido que el resto de las
-- tablas (todo el equipo autenticado ve y edita; nadie anonimo entra).
-- ---------------------------------------------------------------------
alter table public.contratos enable row level security;

drop policy if exists "contratos_select_equipo" on public.contratos;
create policy "contratos_select_equipo" on public.contratos
  for select to authenticated using (true);

drop policy if exists "contratos_insert_equipo" on public.contratos;
create policy "contratos_insert_equipo" on public.contratos
  for insert to authenticated with check (true);

drop policy if exists "contratos_update_equipo" on public.contratos;
create policy "contratos_update_equipo" on public.contratos
  for update to authenticated using (true) with check (true);

drop policy if exists "contratos_delete_equipo" on public.contratos;
create policy "contratos_delete_equipo" on public.contratos
  for delete to authenticated using (true);

grant select, insert, update, delete on public.contratos to authenticated;
