-- =====================================================================
-- Cotizador Fumigaciones AECO — Configuración de base de datos Supabase
-- =====================================================================
-- Cómo usar este archivo:
--   1. Entra a tu proyecto en https://supabase.com/dashboard
--   2. Ve a "SQL Editor" > "New query"
--   3. Pega TODO este archivo y presiona "Run"
--   4. Avísame cuando termine para seguir con la creación de usuarios
--
-- Este script es seguro de volver a correr (usa IF NOT EXISTS / OR REPLACE
-- en la mayoría de los objetos), pero si ya lo corriste una vez y solo
-- quieres revisar qué contiene, no hay problema en volver a ejecutarlo.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. TABLAS
-- ---------------------------------------------------------------------

-- Clientes de la empresa (compartidos entre todo el equipo)
create table if not exists public.clientes (
  id               uuid primary key default gen_random_uuid(),
  nombre           text not null,
  telefono         text,
  email            text,
  direccion        text,
  contacto         text,
  zona             text,               -- Monterrey / Guadalupe / Escobedo / San Nicolás / Santa Catarina / Apodaca / San Pedro / García
  categoria        text,               -- Residencial / Empresarial / Industrial
  creado_por       uuid references auth.users(id),
  fecha_creacion   timestamptz not null default now()
);

-- Cotizaciones. "datos" guarda el objeto JSON completo tal como lo arma
-- hoy el formulario (plagas, áreas, póliza, precios, IVA, recomendaciones,
-- etc.) para no perder ningún detalle; las columnas sueltas son solo para
-- poder filtrar/ordenar rápido sin tener que leer todo el JSON.
create table if not exists public.cotizaciones (
  id                  uuid primary key default gen_random_uuid(),
  folio               bigint generated by default as identity unique,
  cliente_id          uuid references public.clientes(id),
  datos               jsonb not null,
  estado              text not null default 'Pendiente'
                       check (estado in ('Pendiente', 'Cerrada', 'Perdida')),
  vendedor            text,
  creado_por          uuid references auth.users(id),
  fecha_creacion      timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

-- Un perfil por usuario de Supabase Auth (rol y estatus del equipo)
create table if not exists public.perfiles_usuario (
  id       uuid primary key references auth.users(id) on delete cascade,
  nombre   text,
  rol      text not null default 'vendedor'
           check (rol in ('dueño', 'vendedor', 'tecnico', 'asistente')),
  activo   boolean not null default true
);

-- Bitácora de inicios de sesión (exitosos y fallidos)
create table if not exists public.registro_accesos (
  id            uuid primary key default gen_random_uuid(),
  usuario_id    uuid references auth.users(id),
  email         text not null,
  fecha_hora    timestamptz not null default now(),
  exitoso       boolean not null,
  ip_origen     text,   -- el navegador no expone la IP pública real; queda null salvo que se agregue un servicio externo
  user_agent    text
);

-- Configuración de la empresa (datos de contacto, textos de la cotización
-- impresa y costos base de la calculadora de "Precio sugerido"). Es una
-- sola fila compartida por todo el equipo — nadie tiene su propia copia.
create table if not exists public.configuracion_empresa (
  id                      smallint primary key default 1 check (id = 1),
  nombre                  text,
  telefono                text,
  direccion               text,
  email                   text,
  licencia_sanitaria      text,
  codigo_documento        text,
  horario_servicio        text,
  personal_tecnico_texto  text,
  logo                    text,   -- imagen del logo como data URI base64
  costo_biothrine         numeric,
  costo_termidol          numeric,
  costo_cirano            numeric,
  costo_combinacion       numeric,
  costo_mano_obra_min     numeric,
  costo_administrativo    numeric,
  costo_por_km            numeric,
  actualizado_por         uuid references auth.users(id),
  fecha_actualizacion     timestamptz not null default now()
);

-- Fila única inicial con los datos reales de Fumigaciones AECO (si ya
-- existe una fila con id=1 no se toca, para no pisar cambios previos).
insert into public.configuracion_empresa (
  id, nombre, telefono, direccion, email, licencia_sanitaria, codigo_documento,
  horario_servicio, personal_tecnico_texto,
  costo_biothrine, costo_termidol, costo_cirano, costo_combinacion,
  costo_mano_obra_min, costo_administrativo, costo_por_km
) values (
  1,
  'Fumigaciones AECO',
  '+52 (81) 2718 0500',
  'Av. Alfonso Reyes No. 2905, Col. Balcones de Alta Vista, Monterrey, N.L. C.P. 64770',
  'info@fumigacionesaeco.com',
  'Lic. Sanitaria N° 18 AP 19 039 0401',
  'F-VTS-003-01',
  'Lunes a viernes de 9:00 a 5:30pm. Servicio fuera de este horario genera cargo adicional.',
  'Nuestro personal técnico es especialmente capacitado por empresas certificadas por la Secretaría del Trabajo y Previsión Social (STPS). Fumigaciones AECO asume total responsabilidad del personal que efectuará los trabajos contratados, sin generar ningún vínculo laboral con su empresa. Técnicos certificados con licencia sanitaria vigente. Equipo de protección personal (EPP) completo en cada servicio.',
  900, 650, 700, 750,
  1.20, 64, 1.50
)
on conflict (id) do nothing;

-- Mantener fecha_actualizacion al día en cada cambio (cotizaciones y
-- configuración de la empresa). La función se crea PRIMERO: los triggers
-- que la usan deben ir después, o Postgres se queja de que no existe.
create or replace function public.actualizar_fecha_actualizacion()
returns trigger
language plpgsql
as $$
begin
  new.fecha_actualizacion = now();
  return new;
end;
$$;

drop trigger if exists trg_cotizaciones_fecha_actualizacion on public.cotizaciones;
create trigger trg_cotizaciones_fecha_actualizacion
  before update on public.cotizaciones
  for each row execute function public.actualizar_fecha_actualizacion();

drop trigger if exists trg_configuracion_fecha_actualizacion on public.configuracion_empresa;
create trigger trg_configuracion_fecha_actualizacion
  before update on public.configuracion_empresa
  for each row execute function public.actualizar_fecha_actualizacion();


-- ---------------------------------------------------------------------
-- 2. AUTO-CREAR PERFIL AL REGISTRAR UN USUARIO NUEVO
-- ---------------------------------------------------------------------
-- Cuando crees un usuario nuevo en Authentication > Users, este trigger
-- le crea automáticamente su fila en perfiles_usuario con rol 'vendedor'
-- por defecto. Entra a la tabla perfiles_usuario y cambia el rol a
-- 'dueño', 'tecnico' o 'asistente' según corresponda a cada persona.

create or replace function public.manejar_usuario_nuevo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfiles_usuario (id, nombre, rol, activo)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nombre', split_part(new.email, '@', 1)),
    'vendedor',
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_usuario_nuevo on auth.users;
create trigger trg_usuario_nuevo
  after insert on auth.users
  for each row execute function public.manejar_usuario_nuevo();


-- ---------------------------------------------------------------------
-- 3. FUNCIÓN AUXILIAR: ¿el usuario actual es dueño?
-- ---------------------------------------------------------------------
create or replace function public.es_dueno()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.perfiles_usuario
    where id = auth.uid() and rol = 'dueño' and activo = true
  );
$$;


-- ---------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------

alter table public.clientes enable row level security;
alter table public.cotizaciones enable row level security;
alter table public.perfiles_usuario enable row level security;
alter table public.registro_accesos enable row level security;
alter table public.configuracion_empresa enable row level security;

-- clientes: cualquier usuario autenticado ve, crea, actualiza y borra
-- (trabajo en equipo — todos comparten la misma cartera de clientes).
drop policy if exists "clientes_select_equipo" on public.clientes;
create policy "clientes_select_equipo" on public.clientes
  for select to authenticated using (true);

drop policy if exists "clientes_insert_equipo" on public.clientes;
create policy "clientes_insert_equipo" on public.clientes
  for insert to authenticated with check (true);

drop policy if exists "clientes_update_equipo" on public.clientes;
create policy "clientes_update_equipo" on public.clientes
  for update to authenticated using (true) with check (true);

drop policy if exists "clientes_delete_equipo" on public.clientes;
create policy "clientes_delete_equipo" on public.clientes
  for delete to authenticated using (true);

-- cotizaciones: mismo criterio de equipo compartido (incluye actualizar
-- estado y eliminar, que ya son funciones existentes del cotizador).
drop policy if exists "cotizaciones_select_equipo" on public.cotizaciones;
create policy "cotizaciones_select_equipo" on public.cotizaciones
  for select to authenticated using (true);

drop policy if exists "cotizaciones_insert_equipo" on public.cotizaciones;
create policy "cotizaciones_insert_equipo" on public.cotizaciones
  for insert to authenticated with check (true);

drop policy if exists "cotizaciones_update_equipo" on public.cotizaciones;
create policy "cotizaciones_update_equipo" on public.cotizaciones
  for update to authenticated using (true) with check (true);

drop policy if exists "cotizaciones_delete_equipo" on public.cotizaciones;
create policy "cotizaciones_delete_equipo" on public.cotizaciones
  for delete to authenticated using (true);

-- perfiles_usuario: cada quien ve su propio perfil; el dueño ve todos.
-- No se permite insert/update/delete desde la app (se administra en el
-- dashboard de Supabase o vía el trigger de usuario nuevo).
drop policy if exists "perfiles_select_propio" on public.perfiles_usuario;
create policy "perfiles_select_propio" on public.perfiles_usuario
  for select to authenticated using (id = auth.uid());

drop policy if exists "perfiles_select_dueno" on public.perfiles_usuario;
create policy "perfiles_select_dueno" on public.perfiles_usuario
  for select to authenticated using (public.es_dueno());

-- registro_accesos: CUALQUIERA puede insertar (incluso un login fallido,
-- donde todavía no hay sesión autenticada, cae bajo el rol "anon"). Solo
-- el dueño puede leer o borrar la bitácora.
drop policy if exists "accesos_insert_publico" on public.registro_accesos;
create policy "accesos_insert_publico" on public.registro_accesos
  for insert to anon, authenticated with check (true);

drop policy if exists "accesos_select_dueno" on public.registro_accesos;
create policy "accesos_select_dueno" on public.registro_accesos
  for select to authenticated using (public.es_dueno());

drop policy if exists "accesos_delete_dueno" on public.registro_accesos;
create policy "accesos_delete_dueno" on public.registro_accesos
  for delete to authenticated using (public.es_dueno());

-- configuracion_empresa: todo el equipo autenticado LEE la misma
-- configuración (logo, datos de contacto, costos base de la
-- calculadora); solo el dueño puede modificarla, para que nadie cambie
-- sin querer los precios base de todos.
drop policy if exists "config_select_equipo" on public.configuracion_empresa;
create policy "config_select_equipo" on public.configuracion_empresa
  for select to authenticated using (true);

drop policy if exists "config_update_dueno" on public.configuracion_empresa;
create policy "config_update_dueno" on public.configuracion_empresa
  for update to authenticated using (public.es_dueno()) with check (public.es_dueno());

drop policy if exists "config_insert_dueno" on public.configuracion_empresa;
create policy "config_insert_dueno" on public.configuracion_empresa
  for insert to authenticated with check (public.es_dueno());


-- ---------------------------------------------------------------------
-- 5. PERMISOS BASE (GRANT)
-- ---------------------------------------------------------------------
-- En Postgres, RLS solo FILTRA filas; antes de eso, el rol necesita el
-- permiso base sobre la tabla o Postgres rechaza con "permission denied
-- for table X" sin siquiera llegar a evaluar las políticas. Este era el
-- paso que faltaba: las políticas ya estaban bien, pero ningún rol tenía
-- concedido el permiso de base para usarlas.

grant usage on schema public to authenticated, anon;

grant select, insert, update, delete on public.clientes        to authenticated;
grant select, insert, update, delete on public.cotizaciones    to authenticated;
grant select                          on public.perfiles_usuario to authenticated;
grant select, delete                  on public.registro_accesos to authenticated;
grant insert                          on public.registro_accesos to authenticated, anon;
grant select, insert, update          on public.configuracion_empresa to authenticated;


-- ---------------------------------------------------------------------
-- Listo. Después de correr esto:
--   1. Ve a Authentication > Users > "Add user" y crea una cuenta para
--      cada persona del equipo (email + password).
--   2. Ve a Table Editor > perfiles_usuario y ajusta la columna "rol"
--      de cada quien ('dueño', 'vendedor', 'tecnico' o 'asistente').
--   3. Avísame y probamos el login desde el cotizador.
-- ---------------------------------------------------------------------
